### ISSUE TITLE
Support font, font size, and text colour in WYSIWG mode by using html syntax in markdown. 

### ISSUE THREAD

**Issue by TheoMcCabe** [Vanessa219/vditor#1511]
In order to increase the functionality of the editor - it would be great if it supported fonts and colors using HTML 

A proposed solution would be allowing the user to paste 

`<span style="color:red; font-family: 'Bebas Neue'; font-size: 4em;">red?</span>` and this render as red text  in the correct font 

This already works in side by side editor mode but would be awesome in WSIWYG - just using buttons

**Comment by 88250** [comment]
Sorry, although HTML is defined in the CommonMark specification, we do not want to provide extensive support at the editor level, because this will seriously reduce the versatility of Markdown, thank you.

**Comment by TheoMcCabe** [comment]
Fair enough - i understand. 

If i wanted to extend this project to achieve this feature -  is there a way i can do so without forking the code? E.g. a way to provide custom markdown rendering as options to vditor / lute? 

Thank you

**Comment by 88250** [comment]
It is almost difficult to implement. Vditor/Lute is relatively complex. It is not so easy to implement supporting syntax extensions. The workload is relatively large, because the parsing and processing of regular Markdown markers must be taken into account, and many trivial situations need to be covered. I recommend that if you want to do an editor with similar functions, it is better to find an HTML editor and add support for some Markdown markers instead of using a Markdown editor to be compatible with HTML input. Thanks for the discussion.
