### ISSUE TITLE
Example 31

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#180]
https://github.github.com/gfm/#example-31
```
- Foo
- * * *
```

![Example31](https://user-images.githubusercontent.com/15811943/75265344-62b64c00-57b6-11ea-8df2-6b0befe12282.gif)

```
- ***
* ---
```

Is there a reason to handle `===` in isHrMD and `* ---` in SpinVditorDOM?
`===` is changed after typing `enter`, but `* ---` is changed without `enter`.
I think `enter` is better.

**Comment by 88250** [comment]
> Is there a reason to handle === in isHrMD and * --- in SpinVditorDOM?

Because parsing `<li>` is complicated, there are many rules to follow by, so we need Lute to handle it. Instead, parsing `<hr>` is simpler, and Vditor needs to decide when to parse. For example, when the user types a space,  some times need to parse but some times need not be.  

**When** needs to parse is the core user experience, we should focus on it always. Our guideline is *instant* as much as possible. The Setext Heading (`---` and `===`) support just improved, maybe rendered without typing `enter` in the future.  

Thank you for these suggestions, we keep moving!
